#ifndef ECC_LEXER_H
#define ECC_LEXER_H

#include <stddef.h>

typedef enum {
  TOKEN_STAR,
  TOKEN_SLASH,

  TOKEN_COLON,
  TOKEN_COMMA,
  TOKEN_DOT,
  TOKEN_SEMICOLON,

  TOKEN_BRACE_LEFT,
  TOKEN_BRACE_RIGHT,
  TOKEN_BRACKET_LEFT,
  TOKEN_BRACKET_RIGHT,
  TOKEN_PAREN_LEFT,
  TOKEN_PAREN_RIGHT,

  TOKEN_BANG,
  TOKEN_BANG_EQUAL,
  TOKEN_EQUAL,
  TOKEN_EQUAL_EQUAL,
  TOKEN_GREATER,
  TOKEN_GREATER_EQUAL,
  TOKEN_PLUS,
  TOKEN_PLUS_EQUAL,
  TOKEN_PLUS_PLUS,
  TOKEN_LESS,
  TOKEN_LESS_EQUAL,
  TOKEN_MINUS,
  TOKEN_MINUS_EQUAL,
  TOKEN_MINUS_MINUS,
  TOKEN_ARROW,

  TOKEN_FLOAT_LITERAL,
  TOKEN_INTEGER_LITERAL,
  TOKEN_IDENTIFIER,
  TOKEN_STRING,

  TOKEN_KEYWORD_AUTO,
  TOKEN_KEYWORD_BREAK,
  TOKEN_KEYWORD_CASE,
  TOKEN_KEYWORD_CHAR,
  TOKEN_KEYWORD_CONST,
  TOKEN_KEYWORD_CONTINUE,
  TOKEN_KEYWORD_DEFAULT,
  TOKEN_KEYWORD_DO,
  TOKEN_KEYWORD_DOUBLE,
  TOKEN_KEYWORD_ELSE,
  TOKEN_KEYWORD_ENUM,
  TOKEN_KEYWORD_EXTERN,
  TOKEN_KEYWORD_FLOAT,
  TOKEN_KEYWORD_FOR,
  TOKEN_KEYWORD_GOTO,
  TOKEN_KEYWORD_IF,
  TOKEN_KEYWORD_INT,
  TOKEN_KEYWORD_LONG,
  TOKEN_KEYWORD_REGISTER,
  TOKEN_KEYWORD_RETURN,
  TOKEN_KEYWORD_SHORT,
  TOKEN_KEYWORD_SIGNED,
  TOKEN_KEYWORD_SIZEOF,
  TOKEN_KEYWORD_STATIC,
  TOKEN_KEYWORD_STRUCT,
  TOKEN_KEYWORD_SWITCH,
  TOKEN_KEYWORD_TYPEDEF,
  TOKEN_KEYWORD_UNION,
  TOKEN_KEYWORD_UNSIGNED,
  TOKEN_KEYWORD_VOID,
  TOKEN_KEYWORD_VOLATILE,
  TOKEN_KEYWORD_WHILE,
} token_kind_e;

typedef struct {
  token_kind_e kind;
  const char *lexeme;
  size_t lexeme_length;
  size_t line;
  size_t column;
} token_t;

typedef struct {
  const char *source;
  const char *current;
  size_t line;
  size_t column;
} lexer_t;

token_t lexer_next_token(lexer_t *lexer);
void lexer_skip_whitespace(lexer_t *lexer);

#endif
